<?php

namespace Database\Seeders;

use App\Models\Status;
use Illuminate\Support\Str;
use App\Models\ElementSetting;
use Illuminate\Database\Seeder;

class ElementSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Setting, Type id 1: Province
        foreach ($this->provincesList() as $province) {
            $this->createNew(1,$province, "");
        }
        // Setting, Type id 2: Site
        foreach ($this->sitesList() as $site) {
            $this->createNew(2,$site, "");
        }

        // Setting, Type id 3: Centre Technique
        foreach ($this->centresTechniquesList() as $ct) {
            $this->createNew(3,$ct, "");
        }

        // Setting, Type id 4: Type Pylône
        foreach ($this->typepylonesList() as $typepylone) {
            $this->createNew(4,$typepylone, "");
        }

        // Setting, Type id 5: Type Site
        foreach ($this->typesiteList() as $typesite) {
            $this->createNew(5,$typesite, "");
        }
    }
    private function createNew($setting_type_id, $nom, $description) {
        ElementSetting::create(['element_setting_type_id' => $setting_type_id,'nom' => $nom, 'code' => Str::slug($nom, '-'), 'description' => $description,'status_id' => Status::default()->first()->id]);
    }

    private function typesiteList() {
        return [
            'Gabon Telecom', 'Airtel', 'Perinco',
        ];
    }

    private function provincesList() {
        return [
            'ESTUAIRE','WOLEU-NTEM','OGOOUE-MARITIME','HAUT-OGOOUE','OGOOUE-IVINDO','OGOOUE-LOLO','NGOUNIE','NYANGA','MOYEN-OGOOUE'
        ];
    }

    private function typepylonesList() {
        return [
            'Auto-Stable', 'Haubanné', 'Pylonet Terrasse', 'Terrasse + Mats', 'Terrasse + Pylonet', 'Mats',
        ];
    }

    private function centresTechniquesList() {
        return [
            'Cluster Angondjé',
            'OYEM',
            'PORT-GENTIL',
            'OKONDJA',
            'Cluster Owendo/Mindoube',
            'MAKOKOU',
            'Cluster Centre ville',
            'Cluster Estuaire',
            'Cluster Gros Bouquet',
            'MOANDA',
            'FRANCEVILLE',
            'KOULA-MOUTOU',
            'BOOUE',
            'Cluster Nzeng Ayong',
            'MOUILA',
            'TCHIBANGA',
            'NDJOLE',
            'LAMBARENE',
            'GAMBA',
            'MANDJI',
            'Cluter Estuaire',
        ];
    }

    private function sitesList() {
        return [
            '1ER CAMPEMENT',
            'ABANGSI',
            'ABELASSI',
            'ABELLA',
            'ABENELANG',
            'ABOUMI',
            'ACAE',
            'ADOUE',
            'AEROPORT POG',
            'AERPORT CDMA',
            'AGENCE CENTREVILLE',
            'AGENCE PRINCIPALE',
            'AGRICOLE',
            'AIR FRANCE',
            'AKAM ESSATOUK',
            'AKEBE',
            'AKEBE VILLE',
            'AKEMINDJO',
            'AKIENI',
            'AKILIBA',
            'NKOK',
            'BAKOUAKA',
            'AKOURNAM III',
            'AKOURNAM SNI',
            'AKOURNAME',
            'AKOURNAME II',
            'ALANGA',
            'ALEN MABOUM',
            'ALENAKIRI',
            'ALIBANDENG',
            'ALIZEE',
            'ALLIANCE',
            'AMBOWE II',
            'ANDJOGO',
            'ANGONDJE',
            'ANGONDJE 1ER CITE',
            'ANGONDJE CHATEAU',
            'ANGONDJE INTRACO',
            'ANGONDJE MARSEILLE',
            'ANGONDJE STADIUM',
            'ANGONDJE STADIUM I',
            'ANGONDJE STADIUM II',
            'ANGONDJE VILLAGE',
            'ANGORI',
            'AGNIZOCK VILLAGE',
            'AOULATOCK',
            'ARAMBO',
            'ARCHIVES NATIONALES',
            'ASECNA',
            'ASSIAMI GT',
            'ASSOK',
            'ASSOK NGOMO',
            'ATSIB NTSOS',
            'AVANG',
            'AVENUE GRAND VILLAGE',
            'AWENDJE',
            'AWOUA',
            'AWOUNGOU',
            'AYANABO',
            'AYIBORVILLE',
            'BAC AVIATION',
            'BAC AVIATION I',
            'BAC AVIATION II',
            'BAKELE',
            'BAKOUDOU',
            'BAKOUESSE',
            'BAKOUMBA',
            'BAKWAKA',
            'BAMBIDIE',
            'BAMBOUCHINE',
            'BANGOS',
            'BARAKA',
            'BAS GUEGUE',
            'BATANGA',
            'BATTERIE IV',
            'BAVANGA',
            'BEAU SEJOUR',
            'BEAU SEJOUR DEUX',
            'BEAU SEJOUR PK8',
            'BEL AIR',
            'BEL AIR II',
            'BELEY',
            'BELINGA',
            'BELLE VUE BII',
            'BELLEVILLE',
            'BEMBICANI',
            'BENGOLA',
            'BENIBANTOU',
            'BIBAS',
            'BIBOMO',
            'BIKELE',
            'BIKELE II',
            'BIKONDOM',
            'BISANGO',
            'BISSEGUE',
            'BISSOBINLAM',
            'BISSOK',
            'BITAM BENEDICTA',
            'BITAM CARREFOUR BIYI',
            'BITAM CONSEIL DEPARTMENT',
            'BITAM FH',
            'BITAM OLAM DIVISION E',
            'BITAM STADIUM',
            'BITEKOU',
            'BOLOSSOVILLE',
            'BONBENDA',
            'BONGOLO',
            'BONGOVILLE GSM',
            'BOUE CENTRAL',
            'BOUE FH',
            'BOUMANGO',
            'BOUNDJOUKOU',
            'CAMP DE BOY',
            'CAMPAGNE',
            'CAP ESTERIAS',
            'CARREFOUR BIFOUN',
            'CARREFOUR BOULINGUI',
            'CARREFOUR CANAL',
            'CARREFOUR GIGI',
            'CARREFOUR GR',
            'CARREFOUR MAKOUKE',
            'CARREFOUR METIS',
            'CARREFOUR SANTA CLARA',
            'CARREFOUR SINDARA',
            'CARREFOUR SOTEGA',
            'CEMAC',
            'CENACOM',
            'CENTRE INSTRUCTION',
            'CENTRE VETO',
            'CES',
            'CHARBONAGE',
            'TRANSFO',
            'CIMAF',
            'CIMENTERIE',
            'CIRMF',
            'CITE ANGONDJE',
            'CITE AWENDJE',
            'CITE DES AILES',
            'CITE DES MARINS',
            'CITE MARINE',
            'CITE MEBIAME',
            'COCOBEACH',
            'COCOBEACH DEUX',
            'COCODI',
            'COCOMOICALA',
            'CONCORDE',
            'CONSEIL DEPARTMENTAL',
            'COSMOPARK',
            'COTE 671',
            'DAMAS',
            'DELTA',
            'DERNIERE HOPITAL',
            'DEUX ECOLE',
            'DIBWANGUI',
            'DINZAMBOU',
            'DJIDJI',
            'DOAN',
            'DRAGAGES',
            'DUNHILL',
            'EBEMESSE',
            'EBOMAN',
            'EBORO',
            'EBORO II',
            'ECOLE NORMALE',
            'EDHZA EBIENG',
            'EGLISE MINGARA',
            'EKOBA',
            'EKOUK',
            'EKWATA',
            'ESSASSA',
            'EVASION',
            'EZANGA',
            'FANGUINDAKA',
            'FCV AEROPORT',
            'FCV EPILA',
            'FCV MAIRIE',
            'FCV MANGOUNGOU',
            'FCV MBAYA',
            'FCV MVENGUE',
            'FCV OGOOUE',
            'FCV OPT',
            'FCV POSTE',
            'FCV POTOS',
            'FCV SABLE',
            'FEN SI',
            'FOPI',
            'FOUGAMOU',
            'FOURPLACE',
            'FRAN GIPANIER',
            'GABON 2000',
            'GABON MINING',
            'GABONVILLE',
            'GAMBA CENTRAL',
            'GAMBA FH',
            'GONGOUE',
            'GROS BOUQUET',
            'GUIDOUMA',
            'HAUT GUE GUE',
            'HEANZO',
            'HIENDJE',
            'HOPITAL',
            'HOPITAL LAMBARENE',
            'HOPITAL MILITAIRE',
            'HOTEL DE VILLE',
            'HOTEL IMPERIAL',
            'HOTEL MERIDIEN',
            'IAI',
            'IAI II',
            'IBANGA POLA',
            'IDOMBO',
            'INTER MINI',
            'ISSAC',
            'IYOKO CAMPEMENT',
            'JEAN VIOLAS',
            'KABALA',
            'KANGAKA',
            'KANGO FH',
            'KANGO GSM',
            'KELE',
            'KEWAGA',
            'KOM',
            'KONDA',
            'KOUCAL',
            'KOUGOULEU',
            'KOULA',
            'KOULA AERO',
            'KOULAMOUTOU',
            'KOULAMOUTOU AEROPORT II',
            'KOULAMOUTOU I',
            'KOUMAGA',
            'KOUMAMEYONG',
            'LABOKA',
            'LALALA',
            'LALALA DROITE',
            'LALARA',
            'LAMBARENE AERO',
            'LAMBARENE FH',
            'LAMBARENE GSM',
            'LAMBARENE TROPO',
            'LAMFOUBOU',
            'LASTOURVILLE',
            'LEBAMBA',
            'LECONI PALACE',
            'LEKINDOU',
            'LECONI',
            'LEKORI',
            'LENGORI',
            'LEON MBA',
            'LIMITE KELE',
            'LIPAKA II',
            'LOLO FH',
            'LOPE OKANDA',
            'LOPE VILLAGE',
            'LOUBOMO',
            'LOUIS',
            'LOUIS CENTER',
            'LOUIS II',
            'LPIG',
            'LYCEE BEL AIR',
            'LYCEE TECHNIQUE',
            'MABOUMINE',
            'MAIRIE',
            'MAKATAMANGOYE',
            'MAKOKOU AIRPORT',
            'MAKOKOU CENTRAL',
            'MAKOKOU FH',
            'MAKOKOU I',
            'MAKOUKE',
            'MANDJI',
            'MANDJI II',
            'MANFOUNGUI',
            'MANGUONDO',
            'MASSIKA',
            'MASUKU USTM',
            'MATORA',
            'MATSATSA',
            'MAVANE EFFACK',
            'MAYUMBA FH',
            'MBAYA',
            'MBE',
            'MBELA',
            'MBIGOU',
            'MBIGOU II',
            'MBOLO III',
            'MBOMO PK22',
            'MBOUGA',
            'MBOUKOU',
            'MEBOLO',
            'MEDANG NKOGHE',
            'MEDOUNEU',
            'MEKAMBO',
            'MELEN',
            'MEYO KYE',
            'MIKOLONGO',
            'MIKOLONGO DEUX',
            'MIKOUMA',
            'MIKOUYI',
            'MIMONGO PK36',
            'MINA',
            'MINDOUBE CITE',
            'MINDOUBE DECHARGE',
            'MINDOUBE III',
            'MINDZI',
            'MINVOUL',
            'MITOUM',
            'MITZIC GSM',
            'MOABI',
            'MOANDA CENTRAL',
            'MOANDA HOTEL',
            'MOANDA RTG',
            'MOANDA SAEN',
            'MOHOBA',
            'MONBELI NDJOLE',
            'MONT BOUET',
            'MONT KANO',
            'MONT MOANDA',
            'MONT TCHAD',
            'MONTALIER',
            'MONTALIER LYCEE',
            'MOPIA GT',
            'MOUILA AGENCE',
            'MOUILA FH',
            'MOUNANA',
            'MOUNANA CITY',
            'MOURINDI',
            'MOUYOL',
            'MOYABI',
            'NDENDE',
            'NDENDE II',
            'NDJOLE CENTRAL',
            'NDJOLE FH',
            'NDJOLE GARE',
            'NDOUGOU',
            'NDZOUGZAP',
            'NGADI',
            'NGOINA',
            'NGOMA',
            'NGOUONI MOOV',
            'NIANAM',
            'NKEMBO',
            'NKOK EBELABANGA',
            'NKOLABONA',
            'NKOLAYOP',
            'NKOLAYOP NKODJE',
            'NKOLNGOUM',
            'NKOLTANG',
            'NKOMELE',
            'NKORALENE',
            'NKOUT',
            'NOMBAKELE II',
            'NOMBAKELE PK33',
            'NSANG ENGONG',
            'NSILE',
            'NTCHENGUE II',
            'NTOUM',
            'NTOUM II',
            'NTSIETE',
            'NZAMALIGHE',
            'NZELA',
            'NZENG AYONG EGLISE',
            'NZENG AYONG KOWEIT',
            'NZENG AYONG MILOSSI',
            'NZENG AYONG OPT',
            'NZENG AYONG VILLAGE',
            'NZENG ECOLE DRAGAGES',
            'NZENG MCD',
            'NZENZELE',
            'NZOGHE EBANG',
            'OBANE',
            'OBIA',
            'OBORILEKOUSSA',
            'OCEAN',
            'OCTRA',
            'OKALA',
            'OKALA CICIBA',
            'OKALA NORD',
            'OKONDJA II',
            'OKANGOVILLE',
            'OKILA',
            'OKOLASSIE PK35',
            'OKOLOVILLE',
            'OKONDJA',
            'OKOUME',
            'OKOUYA',
            'OLAM KANGO',
            'OLAM MANDJI',
            'OLAM MBOUKOU',
            'OLAM MOUTASSOU',
            'OLAM OTOURI BITAM',
            'OLAM PK19',
            'OLOUME BARAKA',
            'OLOUMI',
            'OLOUMI II',
            'OMBOOUE CENTRAL',
            'OMBOUE FH',
            'OMNISPORT',
            'OMOY',
            'ONDILI',
            'ONDOGHO',
            'ONDOGHO II',
            'ONDOGHO III',
            'ONGOUAMA',
            'ONDZEYE',
            'ONGA',
            'ONGUIA',
            'ONKOULA',
            'OPOUNGOU',
            'OPRAG',
            'OSSIELE',
            'OSSKAMA',
            'OTALA',
            'OTOMBI',
            'OTOU',
            'OTOUNDOU',
            'OVAN',
            'OVENG',
            'OWENDO',
            'OYAN',
            'OYEM CENTRAL',
            'OYEM FH',
            'OYEM MFOUL',
            'OYEM NGOUEMA',
            'OYEM RTG',
            'OYEM UNIVERSITE',
            'OYENDZE',
            'OYENI',
            'OZANGUE',
            'PANA',
            'PEDIATRIE',
            'PEPINIERE',
            'PETIT PARIS',
            'PK12',
            'PK12 III',
            'PK13',
            'PK13 II',
            'PK30',
            'PK5',
            'PK5 III',
            'PK5 TERRE NOUVELLE',
            'PK6',
            'PK7 MAKOKOU',
            'PK8 III',
            'PLAINE AYEME',
            'PLEIN CIEL',
            'PLEIN ORETY',
            'POG AIRPORT HOTEL',
            'POG BALISE',
            'POG BANCO',
            'POG CARREFOUR ACERGY',
            'POG COMMISSARIAT',
            'POG FH',
            'POG GENDARMERIE',
            'POG IMPACT EG',
            'POG LOPEZ',
            'POG MATANDA',
            'POG OPRAG',
            'POG QUARTIER CHIC',
            'POG SALSA',
            'POG SNBG',
            'POG SOGARA I',
            'POG STATION TERRIENNE',
            'POINTE DENIS',
            'POLICE ANGONE',
            'POMPIER',
            'PONT AKEBE',
            'POUBARA',
            'POUNGOU POUNGOU',
            'PROMOGABON',
            'QUARTIER BIKELE',
            'QUARTIER SUD',
            'RABI CHECK POINT',
            'RABI KOUNGA',
            'RAZEL',
            'RAZEL DEUX',
            'RELAIS FOUGAMOU',
            'RELAIS GUIDOUMA',
            'RELAIS LEBAMBA',
            'RELAIS MITZIC',
            'RELAIS NDOUGOU',
            'RELAIS YOMBI',
            'REPETEUR COMILOG',
            'ROND POINT NZENG AYONG',
            'RPP',
            'RTG1',
            'SABLIERE',
            'SABLIERE II',
            'SACRE COEUR 1800',
            'SAINTE ANNE',
            'SAINTE MARIE',
            'SAINTE RITA',
            'SAM',
            'SANTA CLARA',
            'SCHEIZER',
            'SENGA FORET',
            'SHM',
            'SIAT BITAM',
            'SIAT GABON',
            'SIBANG',
            'SOBRAGA',
            'SOGARA PLAGE',
            'SASSOMONGO',
            'SOTEGA',
            'SOUBA',
            'STADE AKWAKAM',
            'SUCAF',
            'NTCHENGUE I',
            'TCHIBANGA AERO',
            'TCHIBANGA FH',
            'TCHIBANGA HOPITAL',
            'TCHIBANGA I',
            'TEBE',
            'TGI',
            'TOUGOUTOUGOU',
            'TOULON',
            'TROU DU DIABLE',
            'UOB',
            'VEMBO',
            'VENEZ VOIR',
            'YEFFA',
            'YENE',
            'YOKO',
            'YVES DIGO',
            'ZOOLENDE',
            'BISANGO ENTRACO',
            'KANGO DRAGAGES',
            'NKOK II',
            'NTOUM III',
            'NZOGMITANG',
            'OYAN III',
            'GABON MINING OKONDJA I',
            'GABON MINING OKONDJA II',
            'MOUKOUANGO ',
            'NDINDI',
            'YENZI',
        ];
    }
}
